//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int SiparisId { get; set; }
        public string SiparisKod { get; set; }
        public string SiparisTarih { get; set; }
        public int SiparisUrunId { get; set; }
        public int SiparisUyeId { get; set; }
    
        public virtual Urun Urun { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
